#!/usr/bin/env sh

# abort on errors
set -e

# build
yarn generate

git_version_hash=$(git rev-parse HEAD)

# navigate into the build output directory
cd dist

# echo 'mizikgame.com' > CNAME
# echo "$git_version_hash" > VERSION

git init
git checkout -b master
git add -A
git commit -m 'deploy'

# if you are deploying to https://<USERNAME>.github.io/<REPO>
git push -f git@github.com:velocilab/velocilab.github.io.git master

cd -
